---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deploy-webapp-deploy-overlays-dev # path to the automation
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/webapp/deploy/overlays/dev # This is the current working directory followed
          # by the path you specified to gitops run
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
